# Generated by Django 4.1.1 on 2022-10-01 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_assignexam_delete_assingexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignexam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
