# Generated by Django 4.1.1 on 2022-10-01 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_assignexam_created_at_assignexam_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignexam',
            name='source_exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_assignments', to='exam.exam'),
            preserve_default=False,
        ),
    ]
