# Generated by Django 4.1.1 on 2022-10-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_assignexam_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignexam',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
