# Generated by Django 4.1.1 on 2022-09-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_institution_customuser_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Institution',
        ),
    ]
