# Generated by Django 4.1.1 on 2022-09-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customuser_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.institution'),
            preserve_default=False,
        ),
    ]
