# Generated by Django 4.1.1 on 2022-09-26 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_institution_customuser_institution'),
        ('course', '0002_alter_course_disciplines_alter_course_studants'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.institution'),
        ),
    ]
