# Generated by Django 4.1.1 on 2022-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_discipline_studants_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='disciplines',
            field=models.ManyToManyField(null=True, related_name='courses', to='course.discipline'),
        ),
    ]
